export const YEAR_OPTIONS = Array.from(
  { length: new Date().getFullYear() - 1980 + 1 },
  (_, index) => new Date().getFullYear() - index
)

export const CAR_MAKES = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'Genesis',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Maserati',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'MINI',
  'Mitsubishi',
  'Nissan',
  'Porsche',
  'Ram',
  'Rolls-Royce',
  'Subaru',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo'
]

export const TRIM_OPTIONS = [
  'Base',
  'S',
  'SE',
  'SL',
  'SLT',
  'L',
  'LX',
  'EX',
  'EX-L',
  'Sport',
  'Sport Premium',
  'Touring',
  'Premium',
  'Limited',
  'Platinum',
  'Signature',
  'Elite',
  'R-Line',
  'RS',
  'GT',
  'GT-Line',
  'GTS',
  'XLT',
  'Lariat',
  'King Ranch',
  'Black Label',
  'Titanium',
  'R/T',
  'Trailhawk',
  'M Sport',
  'xDrive',
  'AMG',
  'Apex',
  'Stingray',
  'Z71',
  'Pro',
  'SX',
  'SR5',
  'TRD Off-Road',
  'TRD Pro',
  'Vantage',
  'Grand Touring',
  'Executive',
  'Long Wheelbase',
  'Performance',
  'Prestige',
  'Launch Edition'
]

export const MODEL_OPTIONS: Record<string, string[]> = {
  Acura: ['ILX', 'MDX', 'RDX', 'TLX', 'NSX', 'Integra', 'ZDX', 'RSX', 'RLX'],
  'Alfa Romeo': ['4C', 'Giulia', 'Stelvio', 'Tonale', 'GTV', 'Spider'],
  'Aston Martin': ['DB11', 'Vantage', 'DBX', 'Vanquish', 'Rapide', 'DBS'],
  Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'R8', 'RS5', 'S4', 'S5', 'S6', 'S8', 'TT'],
  Bentley: ['Bentayga', 'Continental', 'Flying Spur', 'Mulsanne', 'Turbo R', 'Arnage'],
  BMW: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'i5', 'i7', 'M2', 'M3', 'M4', 'M5', 'M8', 'XM'],
  Buick: ['Encore', 'Enclave', 'Envista', 'LaCrosse', 'Lucerne', 'Regal', 'Century', 'Electra'],
  Cadillac: ['ATS', 'CT4', 'CT5', 'Escalade', 'XT4', 'XT5', 'XT6', 'XTS', 'SRX', 'CTS', 'Eldorado'],
  Chevrolet: ['Camaro', 'Corvette', 'Cruze', 'Equinox', 'Impala', 'Malibu', 'Silverado', 'Tahoe', 'Traverse', 'Volt', 'Suburban', 'Blazer', 'Trailblazer', 'Bolt EV'],
  Chrysler: ['300', 'Pacifica', 'Voyager', 'PT Cruiser', 'Aspen', 'Sebring', 'Town & Country'],
  Dodge: ['Charger', 'Challenger', 'Durango', 'Journey', 'Ram 1500', 'Viper', 'Magnum'],
  Ferrari: ['488', '812 Superfast', 'F8 Tributo', 'Roma', 'SF90', 'California', 'F430', 'F355', 'Portofino', 'Monza'],
  Fiat: ['500', '500X', '124 Spider', 'Panda', 'Doblo', 'Tipo'],
  Ford: ['Escape', 'Expedition', 'Explorer', 'F-150', 'F-250', 'F-350', 'Focus', 'Mustang', 'Ranger', 'Transit', 'Fusion', 'Bronco', 'Edge', 'Flex', 'C-Max', 'GT'],
  Genesis: ['G80', 'G90', 'GV60', 'GV70', 'GV80', 'G70', 'GV55'],
  GMC: ['Acadia', 'Canyon', 'Sierra', 'Terrain', 'Yukon', 'Jimmy', 'Denali', 'Safari'],
  Honda: ['Accord', 'Civic', 'CR-V', 'CR-Z', 'Fit', 'HR-V', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline', 'Prelude', 'Element'],
  Hyundai: ['Accent', 'Elantra', 'Genesis Coupe', 'Ioniq', 'Kona', 'Palisade', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Venue'],
  Infiniti: ['Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX55', 'QX60', 'QX80', 'G35', 'G37'],
  Jaguar: ['E-PACE', 'F-PACE', 'F-TYPE', 'XE', 'XF', 'XJ', 'I-PACE', 'XK'],
  Jeep: ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Patriot', 'Renegade', 'Wrangler', 'Commander', 'Trackhawk'],
  Kia: ['Forte', 'Optima', 'Rio', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride', 'Carnival', 'Niro', 'EV6'],
  Lamborghini: ['Aventador', 'Huracan', 'Urus', 'Gallardo', 'Murcielago', 'Diablo'],
  'Land Rover': ['Defender', 'Discovery', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Freelander'],
  Lexus: ['ES', 'GS', 'GX', 'IS', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX', 'LC', 'LFA'],
  Lincoln: ['Aviator', 'Corsair', 'MKC', 'MKZ', 'Navigator', 'Nautilus', 'Town Car', 'Continental', 'Mark LT'],
  Maserati: ['Ghibli', 'GranTurismo', 'GranCabrio', 'Levante', 'Quattroporte', 'MC20', 'Spyder'],
  Mazda: ['3', '5', '6', 'CX-3', 'CX-5', 'CX-9', 'CX-30', 'MX-5', 'Mazda2', 'Mazda6', 'RX-7'],
  McLaren: ['570S', '720S', 'GT', 'Artura', '600LT', '765LT'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S-Class', 'SL', 'SLK', 'AMG GT', 'Maybach'],
  MINI: ['Cooper', 'Clubman', 'Countryman', 'Convertible', 'Hardtop', 'John Cooper Works'],
  Mitsubishi: ['Eclipse', 'Eclipse Cross', 'Lancer', 'Mirage', 'Montero', 'Outlander', 'Pajero', 'Galant'],
  Nissan: ['350Z', '370Z', 'Altima', 'Frontier', 'GT-R', 'Maxima', 'Murano', 'Pathfinder', 'Rogue', 'Sentra', 'Titan', 'Versa', 'Xterra', 'Leaf', 'Z'],
  Porsche: ['911', '718 Boxster', '718 Cayman', 'Carrera GT', 'Cayenne', 'Cayman', 'Macan', 'Panther', 'Boxster', 'Taycan', 'Taycan Cross Turismo', '911 Turbo'],
  Ram: ['1500', '2500', '3500', 'ProMaster', 'Dakota', 'Power Wagon'],
  'Rolls-Royce': ['Ghost', 'Phantom', 'Cullinan', 'Wraith', 'Dawn', 'Spectre'],
  Subaru: ['BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'WRX', 'Ascent', 'Tribeca'],
  Tesla: ['Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster', 'Cybertruck'],
  Toyota: ['4Runner', 'Avalon', 'Camry', 'Corolla', 'C-HR', 'Highlander', 'Land Cruiser', 'Matrix', 'Prius', 'RAV4', 'Sequoia', 'Sienna', 'Tacoma', 'Tundra', 'Yaris'],
  Volkswagen: ['Atlas', 'Beetle', 'Golf', 'GTI', 'Jetta', 'Passat', 'Polo', 'Tiguan', 'Touareg', 'Atlas Cross Sport', 'ID.4'],
  Volvo: ['S60', 'S80', 'V60', 'V90', 'XC40', 'XC60', 'XC70', 'XC90', 'C40', 'V40']
}

export const MODEL_OPTIONS_LIST = Array.from(
  new Set(Object.values(MODEL_OPTIONS).flatMap((models) => models))
).sort((a, b) => a.localeCompare(b))
